# Generated by Django 3.0.2 on 2020-06-23 15:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jwt_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investment_date', models.DateField()),
                ('investment_type', models.CharField(choices=[('CH', 'Cash'), ('PN', 'Cash ISA'), ('PN', 'Pension')], default='CH', max_length=2)),
                ('investment_name', models.CharField(max_length=50)),
                ('initial_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investment', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=4)),
                ('company_name', models.CharField(max_length=50)),
                ('primary_exchange', models.CharField(max_length=10)),
                ('isin', models.CharField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_name', models.CharField(max_length=100)),
                ('stock_id', models.ManyToManyField(related_name='wishlist', to='tracker.Stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wishlist', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_bought', models.DateField()),
                ('number_of_shares', models.DecimalField(decimal_places=5, max_digits=10)),
                ('price_per_share', models.DecimalField(decimal_places=5, max_digits=10)),
                ('commission', models.DecimalField(decimal_places=2, max_digits=4)),
                ('stamp_duty', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('account_type', models.CharField(max_length=20)),
                ('broker', models.CharField(max_length=50)),
                ('comment', models.CharField(blank=True, max_length=50)),
                ('sold', models.BooleanField()),
                ('symbol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to='tracker.Stock')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trade', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('investment_id', models.ManyToManyField(blank=True, related_name='portfolio', to='tracker.Investment')),
                ('trade_id', models.ManyToManyField(blank=True, related_name='portfolio', to='tracker.Trade')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HistInvestmentValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('current_value', models.DecimalField(decimal_places=5, max_digits=10)),
                ('investment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='histInvestmentValue', to='tracker.Investment')),
            ],
        ),
    ]
