# Generated by Django 3.0.2 on 2020-06-22 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WishList',
            new_name='Stock',
        ),
    ]
