# Generated by Django 3.0.2 on 2020-06-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_auto_20200628_1734'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='sold',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
